version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:10.1
      - image: circleci/mongo:3.6.4
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
          working_directory: ~/repo/api

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install npm
          command: npm install
          working_directory: ~/repo/api

      - run:
          name: Build
          command: npm run build
          working_directory: ~/repo/api

      - save_cache:
          paths:
            - api/node_modules
          key: v1-dependencies-{{ checksum "api/package.json" }}
      
      - run:
          name: Test
          command: npm run test:ci
          working_directory: ~/repo/api
          environment:
            JEST_JUNIT_OUTPUT: "test-results/junit/js-test-results.xml"

      - store_test_results:
          path: api/test-results

      - persist_to_workspace:
          root: ~/repo
          paths:
            - api

  deploy-job:
    docker:
      - image: juhovee/circleci-node-docker-awsebcli:latest
    
    working_directory: ~/repo
    steps:
      
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: ~/repo

      - run:
          name: Build and push a Docker image to Dockerhub
          working_directory: ~/repo/api
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t juhovee/chatty-api:$TAG -t juhovee/chatty-api .
            docker push juhovee/chatty-api:$TAG

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master