# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1
      - image: circleci/mongo:3.7.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
          working_directory: ~/repo/api

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "api/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install npm
          command: npm install
          working_directory: ~/repo/api

      - run:
          name: Build
          command: npm run build
          working_directory: ~/repo/api

      - save_cache:
          paths:
            - api/node_modules
          key: v1-dependencies-{{ checksum "api/package.json" }}
      
      - run:
          name: Test
          command: npm run test-ci
          working_directory: ~/repo/api
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

#      - run:
#          name: Generate code coverage
#          command: './node_modules/.bin/nyc report --reporter=text-lcov'
#          working_directory: ~/repo/api

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: coverage

#  test:
#    docker:
#      - image: circleci/node:10.1
#      - image: circleci/mongo:3.7.9
#
#    working_directory: ~/repo#
#
#   steps:
#      - checkout
#
#      - run:
#          name: Test
#          command: npm test
#          working_directory: ~/repo/api
#
#      - run:
#          name: Generate code coverage
#          command: './node_modules/.bin/nyc report --reporter=text-lcov'
#          working_directory: ~/repo/api
#
#      - store_test_results:
#          path: test-results
#
#      - store_artifacts:
#          path: coverage

#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master